### ISSUE TITLE
Not loading fonts or favicon

### ISSUE THREAD

**Issue by robertbenjamin** [yoshuawuyts/choo-website#13]
I'm not sure what's changed, but the site doesn't seem to be loading the same font as it used to.

There also isn't any favicon or title.

**Comment by yoshuawuyts** [comment]
haha, yeah the serif font was a bug - apparently slipped through for a
while. We should probs (sooner, not later) migrate to choo v6, new bankai
and get things like the title element right. Thanks for spotting!

**Comment by ungoldman** [comment]
I think this was mostly resolved by #15 & #18. There's another issue for favicon (#5) too.

Thanks @robertbenjamin!
