### ISSUE TITLE
bug(beacon): Uncaught DOMException

### ISSUE THREAD

**Issue by ungoldman** [yoshuawuyts/choo-website#16]
Looks like beacon code merged in #10 fails on chrome:

```
Uncaught DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at nanobeacon (https://choo.io/bundle.js:85:178)
    at https://choo.io/bundle.js:3:1916
```

![screen shot 2017-08-10 at 4 54 21 pm](https://user-images.githubusercontent.com/427322/29196941-940ec774-7dec-11e7-8f06-a0a6f9c277cb.png)

**Comment by yoshuawuyts** [comment]
Oh yeah, that's new in Chrome 60 which was introduced this week. Oops;
should be an open issue on nanobeacon somewhere anticipating this

**Comment by yoshuawuyts** [comment]
Should be fixed!
