### ISSUE TITLE
bug: letter spacing renders differently on dev & prod

### ISSUE THREAD

**Issue by ungoldman** [yoshuawuyts/choo-website#17]
Ok, I am confused. The letter spacing thing is definitely rendering differently between local dev and production (https://choo.io).

<img width="753" alt="screen shot 2017-08-11 at 10 05 51 pm" src="https://user-images.githubusercontent.com/427322/29238058-64eaaf3a-7ee1-11e7-8451-7c7a2c987a40.png">
<img width="785" alt="screen shot 2017-08-11 at 10 05 10 pm" src="https://user-images.githubusercontent.com/427322/29238059-64fd6490-7ee1-11e7-9ea7-9cd6bff6378f.png">

Computed properties seem to be identical but one does not look like the other.

![](https://coolgifs.neocities.org/gifs/14.gif)

**Comment by shibacomputer** [comment]
What version of Chrome are you running?

I got pinged about this on #choo IRC and the first thing that jumped out at me was that I can reproduce the bug cross browser in prod, both in Firefox 54.0.1 and Chrome 60.0.3112.90. (Top in this screencap is FF)
<img width="899" alt="image" src="https://user-images.githubusercontent.com/737950/29242108-df8753d8-7f86-11e7-8352-292cf68f6f07.png">

**Comment by yoshuawuyts** [comment]
Oh, so it's not the properties - it's the amount of whitespace in the letter. Are you running the latest version of `yo-yoify`?

**Comment by ungoldman** [comment]
Fixed in #18
