### ISSUE TITLE
main page potentially seizure inducing

### ISSUE THREAD

**Issue by ghost** [yoshuawuyts/choo-website#37]
when you visit the site in its current state, in the title section there are a lot of rapidly color-changing elements, particularly flashing between a dark color and a light color. i could see this as potentially seizure-inducing, which we would definitely want to avoid

**Comment by yoshuawuyts** [comment]
Limit for this is I believe 3 flashes per second. If we can be under that it should hopefully be good. https://www.epilepsy.org.uk/info/photosensitive-epilepsy/web-design

**Comment by jondashkyle** [comment]
This is an important one—will consider alternate treatments. Perhaps removing the delay between elements and simply loading at once.

**Comment by jondashkyle** [comment]
Hey! I toned down the contrast between the colors while retaining the delay. It feels a bit softer on the eyes. It’s live now—what are your thoughts @pup?

**Comment by ghost** [comment]
@jondashkyle that looks a lot better! thank you
