### ISSUE TITLE
comments in code snippets are difficult to read

### ISSUE THREAD

**Issue by goto-bus-stop** [yoshuawuyts/choo-website#50]
for example, it is really easy to miss the `// 1.` on this line in the form docs:

![image](https://user-images.githubusercontent.com/1006268/35506313-28903544-04e9-11e8-9990-0efcdc3796e1.png)

since comments are often used as anchors i think they should be loud and clear.

**Comment by yoshuawuyts** [comment]
Aye, yeah agree
