### ISSUE TITLE
State Machine Docs: Syntax Error in Example

### ISSUE THREAD

**Issue by xaviervalarino** [yoshuawuyts/choo-website#64]
I've been reading over the docs for Choo and decided to work through the State Machine article—after watching **davidkpiano's** talk on the subject I wanted to get a better feel for how it works.

In the code example the constructor's method is named `next`, but then  further down is called as `transition()`.
```javascript
export class StateMachine {
  constructor (initialState, transitions) {
    this.state = initialState
    this.transitions = transitions
  }

  next (transition) {
    var nextState = this.transitions[this.state][transition]
    if (!nextState) throw new Error(`invalid: ${this.state} -> ${transition}`)
    this.state = nextState
  }
}
```
```javascript
machine.transition('timer')
```

After getting the names to match, I also had to remove `export` and turn the `timer` values into strings to get the example to work (with Node.js).

**Comment by goto-bus-stop** [comment]
Good finds! Would you like to open a PR that fixes those problems? The state machine documentation is in [/content/docs/state-machines/index.md](https://github.com/choojs/website/blob/master/content/docs/state-machines/index.md).

**Comment by xaviervalarino** [comment]
@goto-bus-stop Sure thing! I was considering it when I was submitting the issue, but wasn't sure what the `export` statement was doing. I am not familiar with ES6, but it looks like `module.exports`, so I imagine it is there to illustrate that the state machine should be used as a module?
