### ISSUE TITLE
VHS flicker is painful, possibly harmful

### ISSUE THREAD

**Issue by wavebeem** [yoshuawuyts/choo-website#8]
The "VHS flicker" on page load hurts my eyes, and is possibly a danger for folks with epilepsy. A safer alternative could be simply fading the text in rather than flickering. Or skipping it altogether.

**Comment by yoshuawuyts** [comment]
Heya, yeah I'd be open to change. I quite like the current style, but if it
causes people to feel bad then that's definitely no good. Would a single
brief flicker still be ok tho? We could replace the larger text flickering
with a fade-in perhaps. Thanks for bringing this up; I'll keep this in mind
going forward (:

**Comment by wavebeem** [comment]
WCAG 2.0 says 3 flashes per second is too much, but there's a lot of factors that go into epilepsy for sure http://www.epilepsy.com/learn/triggers-seizures/photosensitivity-and-seizures.

I think a fade-in would look perfect, personally! I think it would still keep that attention grabbing aspect but be less jarring.

**Comment by yoshuawuyts** [comment]
Actually: PR welcome for something that feels good for you - let's collab
on getting this right (:

**Comment by wavebeem** [comment]
Sure, I'll take a look at it later!
